#!/usr/bin/env python3
"""Apply a generated portal package (theme + templates + settings) to a live WP site.

Reads:
  - data/fingerprint-rolls.json: latest roll for the target portal
  - generated/<portal>/: directory with files generated by the LLM via the skill
        (style.css, header.php, footer.php, front-page.php, single.php, archive.php,
         functions.php, assets/css/home.css, etc.)

Applies via SSH + wp-cli:
  1. Installs parent theme if not present
  2. Creates child theme directory
  3. Uploads all generated files
  4. Activates child theme
  5. Applies wp-cli option/menu/widget/permalink configuration based on roll

Usage:
    python scripts/install_portal.py --portal=novoportal.com.br \\
        --ssh-host=<ssh_alias_or_user@host> [--ssh-port=PORT] \\
        --wp-path=/home/user/domains/novoportal.com.br/public_html \\
        [--allow-root] [--dry-run]

Requires:
  - SSH key auth set up to the target host
  - wp-cli installed on the target host
"""
import argparse
import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]


def normalize_remote_path(p):
    """Strip MSYS/Git-Bash path-conversion prefixes and normalize to POSIX.

    Git Bash on Windows auto-rewrites '/home/...' arguments into
    'C:/Program Files/Git/home/...' before they reach Python. This
    function reverses that and ensures forward slashes.
    """
    if not p:
        return p
    p = p.replace("\\", "/")
    # Strip Git-Bash MSYS prefix (e.g. 'C:/Program Files/Git/home/...' -> '/home/...')
    p = re.sub(r"^[A-Za-z]:/Program Files/Git(?=/)", "", p)
    p = re.sub(r"^[A-Za-z]:/msys(?:64|32)?(?=/)", "", p, flags=re.I)
    return p
DB_PATH = ROOT / "data" / "fingerprint-rolls.json"
GEN_ROOT = ROOT / "generated"

PARENT_THEME_SLUGS = {
    "GeneratePress": "generatepress",
    "Blocksy": "blocksy",
    "Kadence": "kadence",
    "Astra": "astra",
    "OceanWP": "oceanwp",
    "Neve": "neve",
    "SmartMag": None,  # not on wp.org, skip auto-install
}

PERMALINK_STRUCTURES = {
    "post_name": "/%postname%/",
    "category_post": "/%category%/%postname%/",
    "year_month_post": "/%year%/%monthnum%/%postname%/",
    "category_year_post": "/%category%/%year%/%postname%/",
    "numeric_post": "/%post_id%/%postname%/",
    "archive_post": "/artigo/%postname%/",
}

DATE_FORMATS = {
    "j_de_F_de_Y": "j \\d\\e F \\d\\e Y",
    "d_m_Y": "d/m/Y",
    "j_F_Y": "j F Y",
    "D_j_de_F": "D, j \\d\\e F",
    "relative": "j \\d\\e F",   # WP doesn't natively do relative; fall back
    "iso_with_relative": "Y-m-d",
}


def find_roll(domain):
    db = json.loads(DB_PATH.read_text(encoding="utf-8"))
    matches = [r for r in db["rolls"] if r["portal"] == domain]
    if not matches:
        sys.exit(f"No roll found for {domain}. Run scripts/roll.py first.")
    return matches[-1]  # latest


def child_slug(domain):
    return "portal-" + domain.replace(".", "-").replace("/", "-")


def run_ssh(host, port, cmd, dry_run=False, allow_root_flag=""):
    """Execute one shell command on the remote host via ssh."""
    full = f"ssh -o StrictHostKeyChecking=no"
    if port:
        full += f" -p {port}"
    full += f" {host} {shlex.quote(cmd)}"
    print(f"  $ {full}", file=sys.stderr)
    if dry_run:
        return ""
    res = subprocess.run(full, shell=True, capture_output=True, text=True)
    if res.returncode != 0:
        print(f"  ERROR (exit {res.returncode}): {res.stderr.strip()}", file=sys.stderr)
    return res.stdout


def scp_to(host, port, local, remote, dry_run=False):
    cmd = f"scp -o StrictHostKeyChecking=no"
    if port:
        cmd += f" -P {port}"
    cmd += f" -r {shlex.quote(str(local))} {host}:{shlex.quote(remote)}"
    print(f"  $ {cmd}", file=sys.stderr)
    if dry_run:
        return
    subprocess.run(cmd, shell=True, check=False)


def stream_to(host, port, local_path, remote_path, dry_run=False):
    """Use 'cat | ssh cat >' to push a single file (works when scp is blocked).

    The remote command is double-quoted so the path can contain spaces. The
    path itself is escaped for double-quote context (no $ or backtick expected
    in WP theme paths)."""
    safe_path = remote_path.replace('\\', '/').replace('"', '\\"')
    remote_cmd = f'cat > "{safe_path}"'
    # Build as argv list (no shell) — avoids Windows cmd.exe path issues with
    # backslashes and lets Python feed stdin from the local file directly.
    argv = ["ssh", "-o", "StrictHostKeyChecking=no"]
    if port:
        argv += ["-p", str(port)]
    argv += [host, remote_cmd]
    print(f"  $ cat {local_path} | ssh ... {host} {shlex.quote(remote_cmd)}",
          file=sys.stderr)
    if dry_run:
        return
    with open(local_path, "rb") as f:
        subprocess.run(argv, stdin=f, check=False)


def wp(host, port, wp_path, args, allow_root, dry_run=False):
    """Run wp-cli on the remote host."""
    base = f"wp --path={shlex.quote(wp_path)} --skip-themes --skip-plugins"
    if allow_root:
        base += " --allow-root"
    cmd = f"{base} {args}"
    return run_ssh(host, port, cmd, dry_run=dry_run)


def install_parent_theme(host, port, wp_path, theme_name, allow_root, dry_run):
    slug = PARENT_THEME_SLUGS.get(theme_name)
    if not slug:
        print(f"  Theme {theme_name}: skipping auto-install (not on wp.org)",
              file=sys.stderr)
        return
    print(f"\n[1/6] Installing parent theme: {slug}")
    out = wp(host, port, wp_path, f"theme list --field=name", allow_root, dry_run)
    if slug in out.split():
        print(f"  Already installed: {slug}", file=sys.stderr)
    else:
        wp(host, port, wp_path, f"theme install {slug}", allow_root, dry_run)


def create_child_theme(host, port, wp_path, domain, theme_name, allow_root, dry_run):
    slug = child_slug(domain)
    parent_slug = PARENT_THEME_SLUGS.get(theme_name) or theme_name.lower()
    print(f"\n[2/6] Creating child theme: {slug} (parent={parent_slug})")
    remote_dir = f"{wp_path.rstrip('/')}/wp-content/themes/{slug}"
    # Use single-quoted brace-expansion so the remote shell expands it; cannot
    # shlex.quote the whole string because that would escape the braces.
    run_ssh(host, port,
            f"mkdir -p '{remote_dir}'/{{assets/css,assets/js,assets/fonts,template-parts,inc}}",
            dry_run=dry_run)
    return slug, remote_dir


def upload_generated_files(host, port, remote_dir, gen_dir, dry_run):
    print(f"\n[3/6] Uploading generated files from {gen_dir}")
    if not gen_dir.exists():
        sys.exit(f"  ERROR: {gen_dir} does not exist. "
                 f"Generate the portal package first.")
    # Pre-create unique parent dirs once each (avoid mkdir per file).
    parents = set()
    files = []
    for local_file in sorted(gen_dir.rglob("*")):
        if local_file.is_dir():
            continue
        rel = local_file.relative_to(gen_dir).as_posix()
        remote = f"{remote_dir.rstrip('/')}/{rel}"
        files.append((local_file, remote))
        parent = str(PurePosixPath(remote).parent)
        if parent and parent != remote_dir:
            parents.add(parent)
    for parent in sorted(parents):
        run_ssh(host, port, f"mkdir -p {shlex.quote(parent)}", dry_run=dry_run)
    for local_file, remote in files:
        stream_to(host, port, local_file, remote, dry_run=dry_run)
    print(f"  Uploaded {len(files)} files")


def activate_child_theme(host, port, wp_path, child_slug_, allow_root, dry_run):
    print(f"\n[4/6] Activating child theme: {child_slug_}")
    wp(host, port, wp_path, f"theme activate {child_slug_}", allow_root, dry_run)


def enable_parent_auto_update(host, port, wp_path, theme_name, allow_root, dry_run):
    """Enable WordPress auto-update on the parent theme (security hardening).

    Applies only to parents that exist on wp.org (Astra, Blocksy, GeneratePress,
    Kadence, Neve, OceanWP). Child themes always stay manual, since they have
    no upstream release channel and the skill manages their contents directly.
    """
    parent_slug = PARENT_THEME_SLUGS.get(theme_name)
    if not parent_slug:
        return
    print(f"\n[4.5/6] Enabling auto-update on parent theme: {parent_slug}")
    wp(host, port, wp_path,
       f"theme auto-updates enable {parent_slug}",
       allow_root, dry_run)


def apply_settings(host, port, wp_path, roll, allow_root, dry_run, preserve_permalink=False):
    print(f"\n[5/6] Applying WP settings from roll")

    # Permalink structure (skip if preserving, to avoid breaking SEO/Antonio URLs)
    if preserve_permalink:
        current = wp(host, port, wp_path, "option get permalink_structure",
                     allow_root, dry_run).strip()
        print(f"  Permalink preserved: {current}")
    else:
        perma_key = roll.get("permalink_structure", "post_name")
        perma_value = PERMALINK_STRUCTURES.get(perma_key, "/%postname%/")
        wp(host, port, wp_path, f"option update permalink_structure {shlex.quote(perma_value)}",
           allow_root, dry_run)
        wp(host, port, wp_path, "rewrite flush", allow_root, dry_run)

    # Date format
    date_key = roll.get("date_format", "d_m_Y")
    date_value = DATE_FORMATS.get(date_key, "d/m/Y")
    wp(host, port, wp_path, f"option update date_format {shlex.quote(date_value)}",
       allow_root, dry_run)

    # Posts per page (homepage)
    posts_per_page = roll.get("posts_per_category", "10")
    wp(host, port, wp_path, f"option update posts_per_page {posts_per_page}",
       allow_root, dry_run)

    # Show on front: posts (we use front-page.php anyway)
    wp(host, port, wp_path, "option update show_on_front posts", allow_root, dry_run)

    # blogname / blogdescription left as-is (manual)
    print("  Settings applied. Logo/blogname not touched (set manually).")


def configure_menus(host, port, wp_path, roll, allow_root, dry_run):
    print(f"\n[6/6] Menu structure: {roll.get('menu_structure_style', 'unknown')}")
    print("  Menu construction is manual (depends on existing categories).")
    print("  Suggested: wp menu create + wp menu item add-custom for each top-level item.")


def cleanup_and_harden(host, port, wp_path, child_slug_, parent_theme, allow_root, dry_run):
    """Skill regra 16: cleanup-and-harden obrigatório pós-deploy. Idempotente.

    Delega para scripts/cleanup_harden.sh (usa apenas awk + sed + wp-cli, sem
    dependência de python no host). O shell script é o source-of-truth.

    Faz: wp-config hardening (DISALLOW_FILE_EDIT, FORCE_SSL_ADMIN, EMPTY_TRASH=7,
    AUTOSAVE=120, WP_DEBUG_DISPLAY=false, CONCATENATE_SCRIPTS=false,
    WP_AUTO_UPDATE_CORE='minor'), plugin/theme auto-update on (child OFF),
    deletar temas inativos, limpar pastas residuais, DB cleanup, inventory.
    Idempotente: rerun é no-op no que já foi feito.
    """
    print("\n[7/7] Cleanup + harden (skill regra 16, obrigatório, idempotente)")
    if dry_run:
        print("  (dry-run: skipped)")
        return

    # Upload script + execute
    script_local = ROOT / "scripts" / "cleanup_harden.sh"
    if not script_local.exists():
        print(f"  ERROR: {script_local} not found")
        return
    remote_script = "/tmp/cleanup_harden.sh"
    scp_to(host, port, script_local, remote_script, dry_run)
    cmd = f"bash {remote_script} {shlex.quote(wp_path)} {shlex.quote(parent_theme)} {shlex.quote(child_slug_)}"
    out = run_ssh(host, port, cmd, dry_run)
    if out:
        for line in out.splitlines():
            print(f"  {line}")
    print("[7/7] Cleanup-and-harden done")
    return  # legacy code abaixo permanece como referência

    # a) wp-config hardening constants — só insere se faltar marker
    wpconfig = f"{wp_path}/wp-config.php"
    backup_cmd = (
        f"if [ ! -f {wpconfig}.bak-skill ]; then "
        f"  cp {wpconfig} {wpconfig}.bak-skill; "
        f"fi"
    )
    run_ssh(host, port, backup_cmd, dry_run)
    # Trocar WP_AUTO_UPDATE_CORE true -> 'minor'
    sed_cmd = (
        f"sed -i \"s|define( 'WP_AUTO_UPDATE_CORE', true );|define( 'WP_AUTO_UPDATE_CORE', 'minor' );|\" {wpconfig}"
    )
    run_ssh(host, port, sed_cmd, dry_run)
    # Inserir bloco hardening (só se marker não existir)
    insert_cmd = (
        f"if ! grep -q 'ADON_HARDENING' {wpconfig}; then "
        f"  awk 'BEGIN{{added=0}}/^\\/\\* That.s all, stop editing/ && !added "
        f"{{print \"/* ===== ADON_HARDENING (wordpress-master) ===== */\"; "
        f"print \"if ( ! defined( \\\"DISALLOW_FILE_EDIT\\\" ) )           define( \\\"DISALLOW_FILE_EDIT\\\", true );\"; "
        f"print \"if ( ! defined( \\\"FORCE_SSL_ADMIN\\\" ) )              define( \\\"FORCE_SSL_ADMIN\\\", true );\"; "
        f"print \"if ( ! defined( \\\"EMPTY_TRASH_DAYS\\\" ) )             define( \\\"EMPTY_TRASH_DAYS\\\", 7 );\"; "
        f"print \"if ( ! defined( \\\"AUTOSAVE_INTERVAL\\\" ) )            define( \\\"AUTOSAVE_INTERVAL\\\", 120 );\"; "
        f"print \"if ( ! defined( \\\"WP_DEBUG_DISPLAY\\\" ) )             define( \\\"WP_DEBUG_DISPLAY\\\", false );\"; "
        f"print \"if ( ! defined( \\\"SCRIPT_DEBUG\\\" ) )                 define( \\\"SCRIPT_DEBUG\\\", false );\"; "
        f"print \"if ( ! defined( \\\"CONCATENATE_SCRIPTS\\\" ) )          define( \\\"CONCATENATE_SCRIPTS\\\", false );\"; "
        f"print \"\"; added=1}} {{print}}' {wpconfig} > {wpconfig}.tmp && mv {wpconfig}.tmp {wpconfig}; "
        f"  echo '  hardening constants inserted'; "
        f"else echo '  hardening already present (skip)'; fi"
    )
    run_ssh(host, port, insert_cmd, dry_run)

    # b) Auto-update on tudo (exceto child theme)
    wp(host, port, wp_path, "plugin auto-updates enable --all", allow_root, dry_run)
    wp(host, port, wp_path, f"theme auto-updates enable {parent_theme}", allow_root, dry_run)
    wp(host, port, wp_path, f"theme auto-updates disable {child_slug_}", allow_root, dry_run)

    # c) Remover temas inativos (preserva active + parent)
    list_cmd = (
        f"wp --path={wp_path} theme list --status=inactive --field=name 2>/dev/null "
        f"| grep -v -E \"^({child_slug_}|{parent_theme})$\" | tr '\\n' ' '"
    )
    inactive_themes = run_ssh(host, port, list_cmd, dry_run)
    if inactive_themes and not dry_run:
        themes_str = inactive_themes.strip()
        if themes_str:
            wp(host, port, wp_path, f"theme delete {themes_str}", allow_root, dry_run)
            print(f"  removed inactive themes: {themes_str}")

    # d) Pastas residuais
    cleanup_paths = [
        f"{wp_path}/wp-content/upgrade/*",
        f"{wp_path}/wp-content/cache",
        f"{wp_path}/wp-content/uploads/imagify-backup",
        f"{wp_path}/wp-content/uploads/backup",
    ]
    for p in cleanup_paths:
        run_ssh(host, port, f"rm -rf {p}", dry_run)

    # e) DB cleanup mínimo (idempotente: trash/drafts/transients expirados)
    wp(host, port, wp_path,
       "post delete $(wp post list --post_status=trash --format=ids --path=" + wp_path + " 2>/dev/null) --force",
       allow_root, dry_run)
    wp(host, port, wp_path,
       "post delete $(wp post list --post_status=auto-draft --format=ids --path=" + wp_path + " 2>/dev/null) --force",
       allow_root, dry_run)
    wp(host, port, wp_path, "transient delete --expired", allow_root, dry_run)
    wp(host, port, wp_path,
       'db query "OPTIMIZE TABLE wp_posts, wp_postmeta, wp_options, wp_comments, wp_users;"',
       allow_root, dry_run)

    # f) Inventory 1:1 — só warning, não aborta
    diff_cmd = (
        f"diff <(wp --path={wp_path} plugin list --field=name 2>/dev/null | sort) "
        f"<(ls {wp_path}/wp-content/plugins/ | grep -v '^index.php$' | sort) "
        f"|| echo '  WARNING: plugin DB/FS mismatch'"
    )
    run_ssh(host, port, diff_cmd, dry_run)

    print("[7/7] Cleanup-and-harden done")


def check_antonio_health(host, port, wp_path, allow_root, dry_run, label):
    """Verify Antonio (QMIX content reception) endpoint is reachable.
    Looks for any registered REST namespace ending in '-api' or starting with
    a hash-prefix (qmix descaracterization pattern)."""
    print(f"\n[Antonio check {label}]")
    out = wp(host, port, wp_path, "rest route list --format=csv",
             allow_root, dry_run)
    if not out:
        print("  Could not list REST routes (target may be dry-run or unreachable).")
        return
    suspicious = [line for line in out.splitlines()
                  if "/artigos" in line or "/v1/artigos" in line]
    if suspicious:
        print(f"  Antonio endpoints found:")
        for line in suspicious[:5]:
            print(f"    {line.strip()}")
    else:
        print(f"  WARNING: no /artigos endpoint detected. Check mu-plugins activation.")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--portal", required=True)
    ap.add_argument("--ssh-host", required=True,
                    help="ssh alias or user@host of the target server")
    ap.add_argument("--ssh-port", type=int, default=None,
                    help="SSH port. Omit to honor ~/.ssh/config for the alias.")
    ap.add_argument("--wp-path", required=True,
                    help="Absolute path to WP install on the target server")
    ap.add_argument("--gen-dir", default=None,
                    help="Local dir with generated files (default: generated/<portal>)")
    ap.add_argument("--allow-root", action="store_true",
                    help="Pass --allow-root to wp-cli (when target user is root)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print all commands without executing")
    ap.add_argument("--preserve-permalink", action="store_true",
                    help="Do NOT change the permalink structure. "
                         "Use for sites with active SEO/backlinks/Antonio integration "
                         "where breaking existing URLs is unacceptable.")
    args = ap.parse_args()

    # Reverse Git-Bash MSYS path conversion that may have mangled --wp-path.
    args.wp_path = normalize_remote_path(args.wp_path)

    roll_entry = find_roll(args.portal)
    roll = roll_entry["roll"]
    theme = roll_entry.get("theme") or "GeneratePress"
    gen_dir = Path(args.gen_dir) if args.gen_dir else GEN_ROOT / args.portal

    print(f"=== Installing portal: {args.portal} ===")
    print(f"    Target: {args.ssh_host}:{args.ssh_port}{args.wp_path}")
    print(f"    Theme:  {theme}")
    print(f"    Gen:    {gen_dir}")
    print(f"    Dry-run: {args.dry_run}")

    check_antonio_health(args.ssh_host, args.ssh_port, args.wp_path,
                         args.allow_root, args.dry_run, label="BEFORE")
    install_parent_theme(args.ssh_host, args.ssh_port, args.wp_path,
                         theme, args.allow_root, args.dry_run)
    cslug, rdir = create_child_theme(args.ssh_host, args.ssh_port, args.wp_path,
                                     args.portal, theme, args.allow_root, args.dry_run)
    upload_generated_files(args.ssh_host, args.ssh_port, rdir, gen_dir, args.dry_run)
    activate_child_theme(args.ssh_host, args.ssh_port, args.wp_path, cslug,
                         args.allow_root, args.dry_run)
    enable_parent_auto_update(args.ssh_host, args.ssh_port, args.wp_path, theme,
                              args.allow_root, args.dry_run)
    apply_settings(args.ssh_host, args.ssh_port, args.wp_path, roll,
                   args.allow_root, args.dry_run,
                   preserve_permalink=args.preserve_permalink)
    configure_menus(args.ssh_host, args.ssh_port, args.wp_path, roll,
                    args.allow_root, args.dry_run)
    cleanup_and_harden(args.ssh_host, args.ssh_port, args.wp_path,
                       cslug, theme.lower(),
                       args.allow_root, args.dry_run)
    check_antonio_health(args.ssh_host, args.ssh_port, args.wp_path,
                         args.allow_root, args.dry_run, label="AFTER")

    print(f"\n=== Done. Visit https://{args.portal}/ to verify. ===")
    print(f"Cleanup-and-harden ja foi aplicado automaticamente (skill regra 16).")
    print(f"Manual ainda pendente (operador):")
    print(f"  - Set the logo/blogname in WP admin (se diferente do default)")
    print(f"  - Build the primary menu using existing categories")
    print(f"  - Verify Customizer (colors are CSS-vars-driven, but check)")
    print(f"  - Run a Lighthouse / PageSpeed test")


if __name__ == "__main__":
    main()
